# Generated by Django 5.1.7 on 2025-03-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_player_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player_count',
        ),
        migrations.AddField(
            model_name='game',
            name='players_list',
            field=models.JSONField(default=list),
        ),
    ]
